softeer5th/be-was-2025

src/main/java/resolver/ResourceResolver.java
src/main/java/resolver/StaticResourceResolver.java
src/main/java/webserver/HTTPMessageParser.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/java/webserver/message/HTTPRequest.java
src/main/java/webserver/message/HTTPVersion.java

1. Thread 기반 응답 처리에서 Concurrent 패키지 기반 응답 처리 (ThreadPoolExecuter를 활용)
2. index.html 응답
-  request를 파싱하는 객체 (HTTPRequestParser)
-  url에 있는 자원을 가져오는 resolver (StaticResourceResolver) 
일단 싱글턴 패턴으로 각 객체를 가져다 사용하도록 구현하였고, 후에 의존성 주입을 위한 객체를 만들어 수정할 예정임.

웹 서버 1단계 - index.html 응답

---

src/main/java/util/HtmlFileReader.java
src/main/java/util/HttpMethod.java
src/main/java/util/RequestInfo.java
src/main/java/util/RequestParser.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. index.html 파일 응답
2. index.html 파일 외 요청 404 처리
3. 객체 책임 분리를 위해 RequestParser, HtmlFileReader util class 정의
4. request 로깅

[웹 서버 1단계] 오주은

---

README.md
src/main/java/webserver/HttpMethod.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/HttpResponse.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/StatusCode.java
src/main/java/webserver/WebServer.java
src/test/java/webserver/HttpRequestTest.java

1. 존재하는 도메인 모델에 HttpRequest, HttpResponse 추가
2. HTTP 메소드와 응답 코드를 Value Object로 보고 Enum Type으로 생성
3. HttpRequest  클래스에 요청 메시지 파싱 책임 부여
4. HttpResponse 클래스에 응답 메시지 설정 및 송신 책임 부여
5. ExecutorService를 활용하여 스레드 풀을 이용한 스레드 관리로 운영체제 레벨의 스레드 생성/삭제 오버헤드 제거

[웹 서버 1단계] 한준호 제출합니다.

---

src/main/java/util/StaticFileProvider.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. Http Request 내용 출력
- BufferedReader 를 통하여 한 줄씩 http request 내용을 읽어 logger 를 통해 출력한다.
2. 정적인 html 파일 응답
- http request header 에서 path 부분을 파싱하여 resources 경로에 파일이 존재하는지 확인한다.
- 파일이 존재한다면 파일을 읽어 출력, 없다면 에러 처리
3. thread -> concurrent 패키지 이용
concurrent 패키지에서 ExecutorService 클래스를 활용하여 쓰레드 풀로 구현한다.

[웹 서버 1단계] - 김현원 제출합니다.

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. index.html 응답 기능 구현
2. HTTP Request 헤더 출력 기능 구현
3. Java Thread 대신 Concurrent 패키지를 사용하도록 수정
4. 메소드 추출
-  헤더 출력 메소드
-  response body 생성 메소드

[웹 서버 1단계] 김동권 제출합니다.

---

.idea/misc.xml
.idea/modules.xml
.idea/modules/be-was-neon.test.iml
build.gradle
src/main/java/util/HttpRequestUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/test/java/util/HttpRequestUtilTest.java
src/test/java/webserver/RequestHandlerTest.java

1. index.html을 응답하도록 수정했습니다.
2. ExecutorService를 이용하여 기존 Thread가 아닌 Concurrent 패키지를 사용하도록 수정했습니다.
---
1번 요구사항을 제대로 보지 못하고 2번으로 넘어가서 2번 과제 내용 커밋 흔적이 있습니다 ㅠ

[웹 서버 1단계] 천성필 제출합니다.

---

README.md
src/main/java/util/FileUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/java/webserver/enums/ContentType.java
src/main/java/webserver/enums/HttpHeader.java
src/main/java/webserver/enums/HttpMethod.java
src/main/java/webserver/enums/HttpStatusCode.java
src/main/java/webserver/enums/HttpVersion.java
src/main/java/webserver/request/HttpRequest.java
src/main/java/webserver/request/HttpRequestParser.java
src/main/java/webserver/response/HttpResponse.java
src/main/java/webserver/response/HttpResponseWriter.java

1. 클라이언트 처리 시 Thread 대신 ExecutorService 사용  
2. GET 요청 시 resources/static 폴더 내의 파일을 응답

[웹 서버 1단계] 박명규

---

src/main/java/util/FileUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. Request에서 파일 주소 파싱한다. 
2. 해당 파일을 찾아서 `byte[]` 형태로 읽어온다. 
3. 읽어온 파일을 응답으로 보내준다. 
Request 헤더의 첫번째 줄 내용만 로거로 출력
1. FileInputStream으로 바이트 단위로 파일을 읽기 위한 스트림을 연다. 
2. BufferedInputStream으로 버퍼를 추가해 성능을 향상시킨다. 
3. 바이트 배열에 읽어들인 파일 데이터를 저장한다. 
``` java
private static final int THREAD_POOL_SIZE = Runtime.getRuntime().availableProcessors();
...
ExecutorService executorService = Executors.newFixedThreadPool(THREAD_POOL_SIZE);
... 
executor.submit(new RequestHandler(connection));
```
- `Executors.newFixedThreadPool()` : 고정된 크기의 스레드 풀
- `executor.submit()` : 인자로 Runnable과 Callable 모두 받을 수 있고, 비동기 연산 결과를 담는 Future 객체를 반환한다.
- 사용하지 않는 import 제거 (nio 패키지)
- 파일 read 기능 FileUtil 클래스로 분리 
- 존재하지 않는 html 파일일 경우 404 에러 반환
- Request에 공백이 여러개인 경우 하나로 처리해 정상 작동하게 함

[웹서버 1단계] 김유리

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. HTTP Request 내용 출력
2. 정적인 HTML 파일 응답 구현
3. Thread사용 코드를 Concurrent 패키지 사용하도록 변경

[웹서버 1단계] 김동현 제출합니다.

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

[구현 기능]
index.html 요청에 대한 처리 구현
HTTP request 헤더 출력 구현
Concurrent를 활용해 쓰레드를 관리하는 기능 구현
유효하지 않은 request에 대한 예외 처리 구현
* 원본 branch 설정을 잘못 하여 다시 PR 요청드립니다.

[웹 서버 1단계] 김선오

---

README.md
src/main/java/webserver/ContentType.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/RequestHandler.java

1. 컨텐츠 타입 추론하도록 설정
- 요청한 URI 의 확장자로 Content-Type 추론
- 확장자가 아무것도 매핑되지 않았을 경우, 406 Not Acceptable 대신 이진 데이터로 간주함

[웹 서버 2단계] 한준호 제출합니다.

---

README.md
src/main/java/model/ContentTypeMapper.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

- 다양한 Content Type 응답 기능
- 존재하지 않는 파일 요청 시 404 Not Found 반환 기능

[웹 서버 2단계] 전경석 제출합니다.

---

src/main/java/util/ContentType.java
src/main/java/util/FileUtil.java
src/main/java/util/HttpRequestParser.java
src/main/java/util/HttpRequestUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/test/java/util/ContentTypeTest.java
src/test/java/util/FileUtilTest.java
src/test/java/util/HttpRequestParserTest.java
src/test/java/util/HttpRequestUtilTest.java

1. (피드백) 단위 테스트 클래스 및 메소드 별로 추가
2. (피드백) 하드코딩 요소 -> enum 및 상수로 변경
3. 404 Error page 예외 처리 추가
4. 파일 유형별로 MIME를 Content-Type에 할당하도록 수정
5. HTTP 요청 문자열 및 파일 처리를 위한 유틸리티 클래스 추가

[웹 서버 2단계] 천성필 제출합니다.

---

src/main/java/util/FileUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/java/webserver/config/ServerConfig.java
src/main/java/webserver/enums/ContentType.java
src/main/java/webserver/enums/HttpMethod.java
src/main/java/webserver/enums/HttpStatusCode.java
src/main/java/webserver/enums/HttpVersion.java
src/main/java/webserver/exception/BadRequest.java
src/main/java/webserver/exception/HttpException.java
src/main/java/webserver/exception/HttpVersionNotSupported.java
src/main/java/webserver/exception/InternalServerError.java
src/main/java/webserver/exception/NotFound.java
src/main/java/webserver/exception/NotImplemented.java
src/main/java/webserver/file/StaticResourceManager.java
src/main/java/webserver/request/HttpRequest.java
src/main/java/webserver/request/HttpRequestParser.java
src/main/java/webserver/request/RequestTarget.java
src/main/java/webserver/response/HttpResponse.java
src/main/java/webserver/response/HttpResponseWriter.java
src/main/java/webserver/response/body/Body.java
src/main/java/webserver/response/body/EmptyBody.java
src/main/java/webserver/response/body/FileBody.java
src/main/java/webserver/response/body/StringBody.java

**feature**
1. 파일 응답 시 확장자를 기반으로 MIME type을 결정하여 응답의 Content-Type 헤더에 지정. 기본 타입은 application/octet-stream
2. status code를 가지는 HttpException 예외를 만들어 validation 등에서 사용. 해당 예외가 발생할 경우 내부의 status code를 응답으로 보냄
3. 디렉터리 경로를 요청받으면 디렉터리 내의 기본 페이지(index.html)을 응답
**refactoring** 
1.  File 작업을 모두 담당하던 FileUtil에서 static 폴더 조작 관련 메서드를 추출하여 StaticResourceManager 클래스로 분리
2. 서버 설정을 중앙화하여 담당하는 ServerConfig 클래스 생성
3. 가독성으로 인해 HttpResponse.Body 관련 클래스들을 별도 클래스로 분리

[웹 서버 2단계] 박명규

---

src/main/java/util/FileUtil.java
src/main/java/webserver/RequestHandler.java

endsWith() 메서드와 if문으로 파일 확장자를 구분하고 적절한 Content-Type을 반환한다.

[웹 서버 2단계] 김유리

---

src/main/java/util/FileUtils.java
src/main/java/util/MimeType.java
src/main/java/util/MimeTypeMapper.java
src/main/java/webserver/RequestHandler.java

1. 다양한 컨텐츠 타입 지원 기능 추가
- enum class를 사용해서 mime type 상수 관리
- MimeTypeMapper class를 사용해서 요청 파일의 확장자에 맞는 Content-type을 선택할 수 있다.
3. http request의 request line을 토큰화하는 기능 추가
- method, target, version으로 토큰화하고 이후 target 을 이용해서 파일의 이름과 확장자를 얻는다.
5. 파일 처리를 위한 fileUtils 클래스를 추가
- 요청에 해당하는 파일을 찾는 메소드 추가

[웹 서버 2단계] 김동권 제출합니다.

---

src/main/java/model/Mime.java
src/main/java/webserver/RequestHandler.java

1. enum Mime 생성하여 다양한 컨텐츠 타입에 대하여 확장자명으로 content-type 반환하는 로직 구현 
2.  RequestHandler에서 request 헤더에서 파일 확장자 반환하는 로직 구현, Mime 사용하는 코드 추가

[웹서버 2단계] 김동현 제출합니다.

---

src/main/java/webserver/ContentTypeMapper.java
src/main/java/webserver/RequestHandler.java

[웹 서버 2단계] 김선오

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/http/HttpRequest.java
src/main/java/webserver/http/HttpResponse.java
src/main/java/webserver/http/HttpStatus.java
src/main/java/webserver/http/MimeType.java
src/main/java/webserver/support/ResourceResolver.java

1. 요구사항에 맞는 MimeType 지원을위해 Map<String,String>을 가지고 있는 class를 작성하였습니다.
2. HTTPStatus를 하드코딩 했던 기존 코드를 변경하여 HttpStatus를 enum 타입 class로 구현하였습니다.
3. requestHandler에서 static file resource serving하는 로직을 모듈화하는 리팩토링 진행하였습니다.

[웹서버 2단계] 김준성

---

src/main/java/servlet/RegisterServlet.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/http/HttpRequest.java
src/main/java/webserver/http/HttpResponse.java
src/main/java/webserver/http/servlet/HttpServlet.java
src/main/java/webserver/http/servlet/ServletInfo.java
src/main/java/webserver/http/servlet/ServletMapper.java
src/main/java/webserver/support/HttpRequestParser.java
src/main/java/webserver/support/ResourceResolver.java
src/main/resources/config/servlet.xml
src/main/resources/static/registration/index.html

동적 처리를 구현하기 위해 Servlet과 Servlet Mapping을 Java Reflection을 통해 간단하게 기능만 구현해 보았습니다.
- service가 오버라이딩 되었으면 해당 service()를 실행하고, service가 오버라이딩 안 되었으면 부모의 service()를 실행해야 하지만, 아직까지는 부모의 service()메소드만 호출.
- Servlet는 아직 doGet()밖에 지원하지 않음.

[웹서버 3단계] 김준성

---

.idea/misc.xml
.idea/modules.xml
build.gradle
src/main/java/model/User.java
src/main/java/webserver/ContentTypeMapper.java
src/main/java/webserver/RequestHandler.java
src/main/resources/static/index.html
src/main/resources/static/registration/index.html
src/test/java/webserver/RequestHandlerTest.java

[구현 기능]
1. 회원가입
- 회원가입 버튼을 누르면 회원가입 입력 폼으로 이동
- 회원 정보를 모두 입력하고 가입 버튼을 누르면 회원가입 절차 처리
- 회원 정보 null값 여부, 아이디 중복 여부 검사 후 이상 없을 경우 데이터베이스에 등록 및 메인 화면으로 redirect
2. 테스트
- 서버가 클라이언트의 요청을 정상적으로 처리하는지 확인하는 테스트 코드 추가

[웹서버 3단계] 김선오

---

README.md
src/main/java/Response/HTTPResponseHandler.java
src/main/java/constant/HTTPCode.java
src/main/java/db/Database.java
src/main/java/manager/UserManager.java
src/main/java/requst/QueryString.java
src/main/java/util/Utils.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/URIHandler.java
src/main/resources/static/registration/index.html
src/test/java/util/UtilsTest.java
src/test/java/webserver/URIHandlerTest.java

- Request 헤더 검증로직은 Utils로 이동
- 헤더파싱, 비즈니스로직 및 response 헤더/바디 작성은 URIHandler로 이동
- 동적URI는 매핑테이블을 통해 reflection으로 메서드를 호출하도록 구현
- 정적 리소스는 URI가 디렉토리를 가리킬 경우 디렉토리 내부의 index.html이 존재할 경우 리턴하도록 구현
- URI Handler의 테스트코드 작성
- 테스트 중 발견한 '/'로 끝나는 경우 발생하는 문제 해결
- Utils의 테스트코드 작성
- header를 파싱할 때 단어가 4개 이상인 예외상황에도 true를 반환하는 코드 수정
- IO를 줄이기 위해 StringBuilder를 통해 writeByte 호출횟수를 줄이도록 수정
- UserManager.signUP 메서드에서 queryString을 파싱하던 것을 QueryString 클래스에서 수행하도록 변경

[웹서버 3단계] 송현성 제출합니다.

---

src/main/java/db/Database.java
src/main/java/handler/CreateUserHandler.java
src/main/java/handler/Handler.java
src/main/java/handler/StaticFileHandler.java
src/main/java/util/FileFinder.java
src/main/java/util/ParameterParser.java
src/main/java/util/RequestParser.java
src/main/java/util/ResponseBuilder.java
src/main/java/util/UserManager.java
src/main/java/util/UserManeger.java
src/main/java/webserver/RequestHandler.java
src/main/resources/static/registration/index.html

1. GET으로 회원가입을 처리하기 위하여 다양한 url에 대해 응답을 구성하는 Handler 인터페이스와 StaticFileHandler 클래스 생성
2. url과 Handler를 매핑하는 ResponseBuilder 클래스 생성
3. 유저 생성을 관리하는 UserManager 클래스 추가
4. Request parameter를 파싱하여 저장하고 반환하는  ParameterParser 클래스 추가
5. CreateUserHandler 클래스 생성하여 /user/create 요청에 대해 회원가입 기능 구현

[웹서버 3단계] 김동현 제출합니다.

---

src/main/java/webserver/FrontController.java
src/main/java/webserver/common/HttpHeaders.java
src/main/java/webserver/enums/ContentType.java
src/main/java/webserver/enums/PageMappingPath.java
src/main/java/webserver/enums/ParsingConstant.java
src/main/java/webserver/handler/RegistrationHandler.java
src/main/java/webserver/handler/ServeStaticFileHandler.java
src/main/java/webserver/request/HttpRequest.java
src/main/java/webserver/request/HttpRequestParser.java
src/main/java/webserver/request/RequestBody.java
src/main/java/webserver/response/HttpResponse.java
src/main/java/webserver/response/body/EmptyBody.java
src/main/java/webserver/response/body/FileBody.java
src/main/java/webserver/response/body/ResponseBody.java
src/main/java/webserver/response/body/StringBody.java
src/main/resources/static/registration/index.html
src/test/java/webserver/request/HttpRequestParserTest.java
src/test/java/webserver/request/HttpRequestTest.java

feature
- Content-Type: x-www-form-urlencoded 타입의 body를 처리하는 기능 추가
- Post 로 회원가입 구현
- Redirection 구현
refactoring
- request body를 미리 읽지 않고 실제로 사용할 때 읽도록 변경
- RequestBody: body를 InputStream으로 저장해두고 필요할 때 읽는 클래스
- Body -> ResponseBody 이름 변경

[웹 서버 4단계] 박명규

---

src/main/java/db/SessionManager.java
src/main/java/exception/HttpErrorCode.java
src/main/java/exception/UserErrorCode.java
src/main/java/handler/UserLoginHandler.java
src/main/java/handler/UserLogoutHandler.java
src/main/java/handler/UserRegisterHandler.java
src/main/java/http/HttpRequestInfo.java
src/main/java/http/HttpResponse.java
src/main/java/http/HttpStatus.java
src/main/java/model/User.java
src/main/java/router/RequestRouter.java
src/main/java/util/FileUtil.java
src/main/java/util/QueryUtil.java
src/main/java/util/SessionUtil.java
src/main/java/webserver/RequestHandler.java
src/main/resources/static/login/failed.html
src/main/resources/static/login/index.html
src/main/resources/static/registration/index.html
src/test/java/handler/StaticFileHandlerTest.java
src/test/java/handler/UserLoginHandlerTest.java
src/test/java/handler/UserLogoutHandlerTest.java
src/test/java/handler/UserRegisterHandlerTest.java
src/test/java/router/RequestRouterTest.java
src/test/java/util/QueryUtilTest.java

- HttpRequestInfo에 요청의 body문을 담을 필드 추가
- RequestHandler에서 요청의 body문을 파싱해오고 로그 찍기
- 회원가입 폼 전송시 POST로 전송
- 회원가입 요청시 Http Method가 POST가 아닌 경우 예외 처리
- 테스트 코드 수정
> 리다이렉션의 경우 회원가입 성공시 registration/success.html 페이지를 불러와서 회원가입 완료 메시지를 띄워주는게 낫다고 판단했습니다. 요구사항을 꼭 지켜야 하는 경우라면 수정하겠습니다!
--- 
- 로그인 실패시 failed.html로 리다이렉션
- 세션 ID를 생성하는 SessionUtil 클래스 추가
- 세션 ID를 관리하는 SessionManager 클래스 추가
- 로그인 기능을 담당하는 UserLoginHandler 클래스 추가
- HttpResponse에 쿠키 헤더 설정하는 메서드 추가
- SessionManager에서 요청으로 받은 세션 ID 삭제 
- 로그아웃 후 index.html로 리다이렉션

[웹 서버 4단계 & 5단계] 김유리

---

src/main/java/servlet/RegisterServlet.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/java/webserver/http/HttpRequest.java
src/main/java/webserver/http/HttpResponse.java
src/main/java/webserver/http/HttpStatus.java
src/main/java/webserver/http/servlet/DuplicateServletMappingException.java
src/main/java/webserver/http/servlet/ServletMapper.java
src/main/java/webserver/support/HttpRequestParser.java
src/main/resources/config/servlet.xml
src/main/resources/static/registration/index.html

- Request Body를 파싱해 byte[] body 필드에 저장
- 302 status 를 통해 Redirect 처리
- ServletMapper를 RequestHandler.java에서 요청마다 생성하던 방식에서 WebServer.java에서 한번 생성후 주입하는 방식으로 변경

[웹서버 4단계] 김준성

---

src/main/java/model/User.java
src/main/java/webserver/ContentTypeMapper.java
src/main/java/webserver/HTTPExceptions.java
src/main/java/webserver/HTTPMethod.java
src/main/java/webserver/HTTPRequestBody.java
src/main/java/webserver/HTTPRequestHeader.java
src/main/java/webserver/HTTPVersion.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/ResponseHandler.java
src/main/resources/static/registration/index.html
src/test/java/webserver/HTTPRequestHeaderTest.java
src/test/java/webserver/RequestHandlerTest.java

[구현 기능]
1. 회원가입 요청 시 POST로 처리
2. HTTP 요청이 들어왔을 때 헤더 및 body 검증 과정 추가
3. 코드 리팩토링

[웹서버 4단계] 김선오

---

.gitignore
README.md
src/main/java/db/Database.java
src/main/java/exception/DuplicateUserIdException.java
src/main/java/exception/MissingUserInfoException.java
src/main/java/http/HttpMethod.java
src/main/java/http/HttpRequest.java
src/main/java/http/HttpResponse.java
src/main/java/http/HttpStatus.java
src/main/java/model/User.java
src/main/java/util/ParsingUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/RequestRouter.java
src/main/java/webserver/WebServer.java
src/main/resources/static/login/index.html
src/main/resources/static/login/login_failed.html
src/main/resources/static/main/index.html
src/main/resources/static/registration/index.html
src/main/resources/static/registration/registration_failed.html

- RequestRouter 구현.
- 회원가입 POST요청 처리
- 회원가입 이후 302 Found 반환하여 리다이렉션
- 로그인 시 sid 쿠키 발급(client), <sid, user> 세션 정보 저장(server)
- 로그아웃 시 세션 정보 삭제, 쿠키 sid=null 으로 재발급

[웹서버 4단계, 5단계] 전경석 제출합니다.

---

src/main/java/entrypoint/UserEntryPoint.java
src/main/java/util/ByteConst.java
src/main/java/webserver/HTTPMessageParser.java
src/main/java/webserver/ResponseWriter.java
src/main/java/webserver/annotation/Body.java
src/main/java/webserver/decoders/ByteDecoder.java
src/main/java/webserver/decoders/PercentDecoder.java
src/main/java/webserver/enumeration/HTTPContentType.java
src/main/java/webserver/enumeration/HTTPStatusCode.java
src/main/java/webserver/message/HTTPRequest.java
src/main/java/webserver/message/HTTPResponse.java
src/main/java/webserver/message/body/BodyParser.java
src/main/java/webserver/message/body/BodyParserFactory.java
src/main/java/webserver/message/body/DefaultBodyParser.java
src/main/java/webserver/message/body/URLEncodedParser.java
src/main/java/webserver/message/header/HeaderParseManager.java
src/main/java/webserver/message/header/parser/AcceptParser.java
src/main/java/webserver/message/header/parser/ContentLengthParser.java
src/main/java/webserver/message/header/parser/ContentTypeParser.java
src/main/java/webserver/message/header/records/ContentTypeRecord.java
src/main/java/webserver/message/record/ResponseData.java
src/main/java/webserver/reader/ByteBufferedReader.java
src/main/java/webserver/reader/ByteStreamReader.java
src/main/java/webserver/resolver/ExceptionResolver.java
src/main/java/webserver/resolver/RequestMethodMapper.java
src/main/java/webserver/resolver/RequestMethodWrapper.java
src/main/java/webserver/resolver/factory/MethodResolverFactory.java
src/main/java/webserver/resolver/records/ParameterMetaInfo.java
src/main/resources/static/registration/index.html

1. 요청 메시지의 Body 파서 추가
2. Body 어노테이션으로 파싱한 Body에서 데이터를 가져와 요청 처리 메서드에 넣어주는 부분 추가
3. 요청 처리 메서드에서 Response 헤더를 외부로 알려주는 기능 추가

[웹 서버 4단계] 송지웅 제출

---

src/main/java/handler/Handler.java
src/main/java/handler/LoginHandler.java
src/main/java/handler/LogoutHandler.java
src/main/java/handler/ReadFileHandler.java
src/main/java/handler/StaticFileHandler.java
src/main/java/util/HtmlContentReplacer.java
src/main/java/util/enums/Page.java
src/main/java/webserver/cookie/CookieManager.java
src/main/java/webserver/request/Request.java
src/main/java/webserver/response/Response.java
src/main/java/webserver/response/ResponseBuilder.java
src/main/resources/static/main/index.html
src/main/resources/static/mypage/index.html

1. html에서 특정 문자열을 치환하는 HtmlContentReplacer 생성
2. html 파일을 HtmlContentReplacer 형식에 맞게 수정
3. StaticFileHandler -> ReadFileHandler로 이름 수정, HtmlContentReplacer 호출 로직 추가
4. 기타 버그 수정

[웹서버 6단계] 김동현 제출합니다.

---

src/main/java/db/Database.java
src/main/java/model/User.java
src/main/java/servlet/HomeServlet.java
src/main/java/servlet/LoginServlet.java
src/main/java/servlet/LogoutServlet.java
src/main/java/servlet/MyPageServlet.java
src/main/java/servlet/RegisterServlet.java
src/main/java/servlet/UpdateUserServlet.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/http/HttpRequest.java
src/main/java/webserver/http/HttpResponse.java
src/main/java/webserver/http/HttpStatus.java
src/main/java/webserver/http/cookie/Cookie.java
src/main/java/webserver/http/servlet/DuplicateServletMappingException.java
src/main/java/webserver/http/servlet/HttpServlet.java
src/main/java/webserver/session/HttpSession.java
src/main/java/webserver/session/SessionManager.java
src/main/java/webserver/support/HttpRequestParser.java
src/main/java/webserver/support/ResourceResolver.java
src/main/resources/static/auth/failed_session_expired.html
src/main/resources/static/index.html
src/main/resources/static/login/failed.html
src/main/resources/static/login/index.html
src/main/resources/static/mypage/failed_empty_field.html
src/main/resources/static/mypage/failed_incorrect_password.html
src/main/resources/static/mypage/index.html
src/main/resources/static/mypage/success.html
src/main/resources/static/registration/failed.html
src/main/resources/static/registration/index.html

- Cookie와 HttpSession 객체를 구현
- Request를 파싱할때 Cookie도 파싱하도록 Parser를 수정
- SessionManager 객체를 구현하고, 싱글톤으로 HttpSession Pool을 관리
- 로그인 로그아웃 서블릿으로 로그인 로그아웃 기능을 구현
- StringBuilder를 이용해서 서블릿내에서 html 구문을 생성하도록 HomeServlet.java을 구현
- 유저 정보 변경을위해 User.java에 changeName() changePassword() 메소드 추가
- UpdateUserServlet.java 유저 정보 변경 기능 구현
- 비밀번호 변경시 다시 로그인하도록 세션 무효화, 비밀번호 변경하지 않고 닉네임만 변경시 세션 유지하고 홈화면으로 리다이렉트

[웹서버 5단계& 6단계] 김준성

---

src/main/java/db/Database.java
src/main/java/webserver/ContentTypeMapper.java
src/main/java/webserver/Cookie.java
src/main/java/webserver/HTTPExceptions.java
src/main/java/webserver/HTTPRequestHeader.java
src/main/java/webserver/HTTPResponseBody.java
src/main/java/webserver/HTTPResponseHeader.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/ResponseHandler.java
src/main/java/webserver/Session.java
src/main/resources/static/index.html
src/main/resources/static/login/index.html
src/main/resources/static/main/index.html
src/main/resources/static/user/login_failed.html

[주요 구현 기능]
1. 동적 HTML 기능 구현
- 로그인 여부에 따라 동일한 HTML 코드를 사용자에게 다르게 표시하는 기능 추가
2. 권한에 따른 요청 처리 기능 구현
- 로그인 권한이 필요한 페이지 접근 시 권한 여부를 체크 후 이에 맞는 처리를 구현

[웹서버 6단계] 김선오

---

src/main/java/handler/dynamic_handler/DynamicHtmlHandler.java
src/main/java/handler/dynamic_handler/HomeDynamicHtmlHandler.java
src/main/java/handler/dynamic_handler/MyPageDynamicHtmlHandler.java
src/main/java/handler/mapping/DynamicHtmlHandlerMapping.java
src/main/java/handler/mapping/RequestHandlerMapping.java
src/main/java/handler/request_handler/FileRequestHandler.java
src/main/java/handler/request_handler/RequestHandler.java
src/main/java/handler/request_handler/UserLoginRequestHandler.java
src/main/java/handler/request_handler/UserLogoutRequestHandler.java
src/main/java/handler/request_handler/UserSignUpRequestHandler.java
src/main/java/http/cookie/Cookie.java
src/main/java/http/enums/HttpStatus.java
src/main/java/http/session/Session.java
src/main/java/http/session/SessionManager.java
src/main/java/webserver/WebServlet.java
src/main/resources/static/global.css
src/main/resources/static/index.html
src/main/resources/static/mypage/index.html
src/test/java/user/SignUpTest.java

1. 동적 html 구현
- DynamicHtmlHandler를 생성하여 동적인 데이터를 추가
- 쿠키로부터 값을 꺼내 세션아이디가 존재한다면 사용자 이름 과 로그아웃 버튼을, 쿠키가 없다면 회원가입, 로그인 버튼을 추가한다.
- html 에 주석을 의미하는 <-- %% --> 을 이용하여 표시
- 마이 페이지를 접근하지 못하게 하기 위해서 쿠키가 없으면 리다이렉션 응답을 한다.

[웹 서버 6단계] 김현원 제출합니다.

---

src/main/java/entrypoint/UserEntryPoint.java
src/main/java/webserver/HTTPMessageParser.java
src/main/java/webserver/ResponseWriter.java
src/main/java/webserver/decoders/PercentDecoder.java
src/main/java/webserver/message/HTTPResponse.java
src/main/java/webserver/message/body/URLEncodedParser.java
src/main/java/webserver/message/record/ResponseData.java
src/main/java/webserver/message/record/SetCookieRecord.java
src/main/java/webserver/resolver/RequestMethodWrapper.java
src/main/resources/static/login/index.html

1. SetCookieRecord 추가 (HTTPResponse, ResponseData 필드에 추가)
2. SetCookie 헤더 작성 부분 추가
세션 스토리지 자체는 추후에 추가 예정

[웹 서버 5단계] 송지웅 제출합니다.

---

src/main/java/entrypoint/UserEntryPoint.java
src/main/java/webserver/HTTPMessageParser.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/annotation/Cookie.java
src/main/java/webserver/message/HTTPRequest.java
src/main/java/webserver/message/header/CookieParser.java
src/main/java/webserver/message/record/ResponseData.java
src/main/java/webserver/reader/TemplateHTMLReader.java
src/main/java/webserver/resolver/RequestMethodWrapper.java
src/main/java/webserver/resolver/factory/MethodResolverFactory.java
src/main/java/webserver/resolver/records/ParameterMetaInfo.java
src/main/java/webserver/session/SessionStorage.java
src/main/java/webserver/writer/ResponseWriter.java
src/main/java/webserver/writer/html/HTMLElement.java
src/main/java/webserver/writer/html/HTMLTag.java
src/main/java/webserver/writer/html/HTMLWriter.java
src/main/java/webserver/writer/html/template/IndexPageWriter.java
src/main/java/webserver/writer/html/template/MyPageWriter.java
src/main/resources/static/index.html

1. 동적 HTML 빌더 추가
2. 세션 스토리지 추가
3. 로그인 정보가 없을 시 redirect 기능 추가

[웹 서버 6단계] 송지웅 제출합니다.

---

build.gradle
src/main/java/db/Database.java
src/main/java/db/manage/CommentManager.java
src/main/java/db/manage/PostManager.java
src/main/java/db/manage/UserManager.java
src/main/java/handler/AddCommentHandler.java
src/main/java/handler/AddPostHandler.java
src/main/java/handler/CreateUserHandler.java
src/main/java/handler/LoginHandler.java
src/main/java/handler/ReadFileHandler.java
src/main/java/handler/UpdatePasswordHandler.java
src/main/java/model/Comment.java
src/main/java/model/Post.java
src/main/java/model/User.java
src/main/java/util/CommentManager.java
src/main/java/util/HtmlContentReplacer.java
src/main/java/util/Parameter.java
src/main/java/util/PostManager.java
src/main/java/util/UserManager.java
src/main/java/util/enums/Page.java
src/main/java/webserver/response/ResponseBuilder.java
src/main/java/webserver/session/Session.java
src/main/resources/static/article/index.html
src/main/resources/static/comment/index.html
src/main/resources/static/index.html
src/main/resources/static/main/index.html
src/main/resources/static/mypage/index.html

1. 데이터베이스를 jdbc와 h2 사용하도록 변경
2. 게시글 추가, 메인페이지에서 페이지네이션 기능 추가
3. 댓글 추가, 모든 댓글 보기 기능 추가
4. mypage에서 유저 비밀번호 변경 기능 추가
5. 기타 버그 수정, 리팩토링

[웹서버 7-1단계] 김동현 제출합니다.

---

README.md
build.gradle
src/main/java/db/Database.java
src/main/java/handler/GetHandler.java
src/main/java/handler/PostHandler.java
src/main/java/http/HttpRequest.java
src/main/java/http/HttpResponse.java
src/main/java/model/Comment.java
src/main/java/model/Post.java
src/main/java/model/User.java
src/main/java/util/SessionUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/RequestRouter.java
src/main/resources/static/article/index.html
src/main/resources/static/comment/index.html
src/main/resources/static/global.css
src/main/resources/static/index.html
src/main/resources/static/login/index.html
src/main/resources/static/mypage/index.html
src/main/resources/static/mypage/update_failed.html
src/main/resources/static/registration/index.html
src/main/resources/static/registration/registration_failed.html

- 게시글 작성 기능
- 게시글 조회 기능
- 이전 글, 다음 글 조회 가능
- 회원정보 수정 기능
** 댓글, 파일 업로드 기능은 아직 구현하지 못했습니다
- Cookie 구분자 수정
- 로깅 -> HttpRequest 생성자 호출 시 로깅하도록 변경
- text block 이용
- 이중 try catch 제거 -> 메서드로 분리

[웹서버 7-1단계] 전경석 제출합니다.

---

src/main/java/db/Database.java
src/main/java/db/manage/ImageManager.java
src/main/java/db/manage/PostManager.java
src/main/java/db/manage/UserManager.java
src/main/java/handler/AddPostHandler.java
src/main/java/handler/ModifyProfileImageHandler.java
src/main/java/handler/ResetProfileImageHandler.java
src/main/java/model/Image.java
src/main/java/model/Post.java
src/main/java/model/User.java
src/main/java/util/HtmlContentReplacer.java
src/main/java/webserver/request/FileBody.java
src/main/java/webserver/request/Request.java
src/main/java/webserver/request/RequestParser.java
src/main/java/webserver/response/ResponseBuilder.java
src/main/resources/static/article/index.html
src/main/resources/static/index.html
src/main/resources/static/main.css
src/main/resources/static/main/index.html
src/main/resources/static/mypage/index.html
src/main/resources/static/registration/index.html

1. 이미지 업로드 기능 구현
2. 유저 프로필 이미지 설정 기능 구현
3. Request 파싱 구조 수정
4. 기타 버그 수정

[웹서버 7-2단계] 김동현 제출합니다.
